package common.cn.kafei.simukraft.network;

import common.cn.kafei.simukraft.network.building.BuildingCacheReloadPacket;
import common.cn.kafei.simukraft.network.building.BuildBoxStartConstructionPacket;
import common.cn.kafei.simukraft.network.building.controlbox.ResidentialControlBoxBoundsUpdatePacket;
import common.cn.kafei.simukraft.network.building.controlbox.ResidentialControlBoxDemolishPacket;
import common.cn.kafei.simukraft.network.building.controlbox.ResidentialControlBoxOccupancyPacket;
import common.cn.kafei.simukraft.network.building.controlbox.ResidentialControlBoxOpenRequestPacket;
import common.cn.kafei.simukraft.network.building.controlbox.ResidentialControlBoxOpenResponsePacket;
import common.cn.kafei.simukraft.network.building.controlbox.ResidentialControlBoxViewUpdatePacket;
import common.cn.kafei.simukraft.network.farmland.FarmlandBoxActionPacket;
import common.cn.kafei.simukraft.network.farmland.FarmlandBoxBoundsRequestPacket;
import common.cn.kafei.simukraft.network.farmland.FarmlandBoxBoundsResponsePacket;
import common.cn.kafei.simukraft.network.farmland.FarmlandBoxOpenRequestPacket;
import common.cn.kafei.simukraft.network.farmland.FarmlandBoxOpenResponsePacket;
import common.cn.kafei.simukraft.network.farmland.FarmlandBoxSetAreaPacket;
import common.cn.kafei.simukraft.network.farmland.FarmlandBoxSetCropPacket;
import common.cn.kafei.simukraft.network.city.chunk.CityChunkBatchPurchasePacket;
import common.cn.kafei.simukraft.network.city.chunk.CityChunkBatchReleasePacket;
import common.cn.kafei.simukraft.network.city.chunk.CityChunkPurchasePacket;
import common.cn.kafei.simukraft.network.city.chunk.CityChunkSyncPacket;
import common.cn.kafei.simukraft.network.city.core.CityCoreCreateCityPacket;
import common.cn.kafei.simukraft.network.city.core.CityCoreManageCityPacket;
import common.cn.kafei.simukraft.network.city.core.CityCoreOpenRequestPacket;
import common.cn.kafei.simukraft.network.city.core.CityCoreOpenResponsePacket;
import common.cn.kafei.simukraft.network.city.map.CityCoreMapRequestPacket;
import common.cn.kafei.simukraft.network.city.map.CityCoreMapResponsePacket;
import common.cn.kafei.simukraft.network.citizen.manage.CityCitizenManageActionPacket;
import common.cn.kafei.simukraft.network.citizen.manage.CityCitizenManageRequestPacket;
import common.cn.kafei.simukraft.network.citizen.manage.CityCitizenManageResponsePacket;
import common.cn.kafei.simukraft.network.city.member.CityCoreMemberActionPacket;
import common.cn.kafei.simukraft.network.city.member.CityCoreMembersRequestPacket;
import common.cn.kafei.simukraft.network.city.member.CityCoreMembersResponsePacket;
import common.cn.kafei.simukraft.network.citizen.info.CitizenBehaviorActionPacket;
import common.cn.kafei.simukraft.network.commercial.CommercialControlBoxOpenRequestPacket;
import common.cn.kafei.simukraft.network.commercial.CommercialControlBoxOpenResponsePacket;
import common.cn.kafei.simukraft.network.commercial.CommercialControlBoxActionPacket;
import common.cn.kafei.simukraft.network.commercial.CommercialControlBoxDemolishPacket;
import common.cn.kafei.simukraft.network.commercial.CommercialTradePacket;
import common.cn.kafei.simukraft.network.commercial.CommercialTradeOpenResponsePacket;
import common.cn.kafei.simukraft.network.hud.HudSyncPacket;
import common.cn.kafei.simukraft.network.industrial.IndustrialControlBoxActionPacket;
import common.cn.kafei.simukraft.network.industrial.IndustrialControlBoxDemolishPacket;
import common.cn.kafei.simukraft.network.industrial.IndustrialControlBoxOpenRequestPacket;
import common.cn.kafei.simukraft.network.industrial.IndustrialControlBoxOpenResponsePacket;
import common.cn.kafei.simukraft.network.industrial.IndustrialControlBoxViewUpdatePacket;
import common.cn.kafei.simukraft.network.logistics.LogisticsBoxActionPacket;
import common.cn.kafei.simukraft.network.logistics.LogisticsClientBoxOpenRequestPacket;
import common.cn.kafei.simukraft.network.logistics.LogisticsClientBoxOpenResponsePacket;
import common.cn.kafei.simukraft.network.logistics.LogisticsServerBoxOpenRequestPacket;
import common.cn.kafei.simukraft.network.logistics.LogisticsServerBoxOpenResponsePacket;
import common.cn.kafei.simukraft.network.logistics.LogisticsWarehouseGridExtractPacket;
import common.cn.kafei.simukraft.network.logistics.LogisticsWarehouseGridInsertPacket;
import common.cn.kafei.simukraft.network.logistics.LogisticsWarehouseGridOpenRequestPacket;
import common.cn.kafei.simukraft.network.logistics.LogisticsWarehouseGridRequestPacket;
import common.cn.kafei.simukraft.network.logistics.LogisticsWarehouseGridResponsePacket;
import common.cn.kafei.simukraft.network.logistics.LogisticsWarehouseGridShiftClickPacket;
import common.cn.kafei.simukraft.network.medical.MedicalControlBoxOpenRequestPacket;
import common.cn.kafei.simukraft.network.medical.MedicalControlBoxOpenResponsePacket;
import common.cn.kafei.simukraft.network.manifest.ManifestTogglePacket;
import common.cn.kafei.simukraft.network.planner.CreatePlanningTaskPacket;
import common.cn.kafei.simukraft.network.planner.PlannerMaterialScanRequestPacket;
import common.cn.kafei.simukraft.network.planner.PlannerMaterialScanResponsePacket;
import common.cn.kafei.simukraft.network.npc.hire.NpcHireAssignPacket;
import common.cn.kafei.simukraft.network.npc.hire.NpcHireFirePacket;
import common.cn.kafei.simukraft.network.npc.hire.NpcHireListRequestPacket;
import common.cn.kafei.simukraft.network.npc.hire.NpcHireListResponsePacket;
import common.cn.kafei.simukraft.network.npc.state.EmploymentStateRequestPacket;
import common.cn.kafei.simukraft.network.npc.state.EmploymentStateResponsePacket;
import common.cn.kafei.simukraft.network.config.ServerConfigSavePacket;
import common.cn.kafei.simukraft.network.path.NpcPathDebugRequestPacket;
import common.cn.kafei.simukraft.network.path.NpcPathDebugSyncPacket;
import common.cn.kafei.simukraft.network.toast.InfoToastPacket;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.neoforge.network.event.RegisterPayloadHandlersEvent;
import net.neoforged.neoforge.network.registration.PayloadRegistrar;

@SuppressWarnings("null")
public final class ModNetwork {
    private static final String NETWORK_VERSION = "23";

    private ModNetwork() {
    }

    @SubscribeEvent
    public static void onRegisterPayloadHandlers(RegisterPayloadHandlersEvent event) {
        PayloadRegistrar registrar = event.registrar(NETWORK_VERSION);
        registrar.playToServer(CityCoreOpenRequestPacket.TYPE, CityCoreOpenRequestPacket.STREAM_CODEC, CityCoreOpenRequestPacket::handle);
        registrar.playToServer(CityCoreCreateCityPacket.TYPE, CityCoreCreateCityPacket.STREAM_CODEC, CityCoreCreateCityPacket::handle);
        registrar.playToServer(CityCoreManageCityPacket.TYPE, CityCoreManageCityPacket.STREAM_CODEC, CityCoreManageCityPacket::handle);
        registrar.playToServer(CityCoreMembersRequestPacket.TYPE, CityCoreMembersRequestPacket.STREAM_CODEC, CityCoreMembersRequestPacket::handle);
        registrar.playToServer(CityCoreMemberActionPacket.TYPE, CityCoreMemberActionPacket.STREAM_CODEC, CityCoreMemberActionPacket::handle);
        registrar.playToServer(CityCitizenManageRequestPacket.TYPE, CityCitizenManageRequestPacket.STREAM_CODEC, CityCitizenManageRequestPacket::handle);
        registrar.playToServer(CityCitizenManageActionPacket.TYPE, CityCitizenManageActionPacket.STREAM_CODEC, CityCitizenManageActionPacket::handle);
        registrar.playToServer(CitizenBehaviorActionPacket.TYPE, CitizenBehaviorActionPacket.STREAM_CODEC, CitizenBehaviorActionPacket::handle);
        registrar.playToServer(CityCoreMapRequestPacket.TYPE, CityCoreMapRequestPacket.STREAM_CODEC, CityCoreMapRequestPacket::handle);
        registrar.playToServer(CityChunkPurchasePacket.TYPE, CityChunkPurchasePacket.STREAM_CODEC, CityChunkPurchasePacket::handle);
        registrar.playToServer(CityChunkBatchPurchasePacket.TYPE, CityChunkBatchPurchasePacket.STREAM_CODEC, CityChunkBatchPurchasePacket::handle);
        registrar.playToServer(CityChunkBatchReleasePacket.TYPE, CityChunkBatchReleasePacket.STREAM_CODEC, CityChunkBatchReleasePacket::handle);
        registrar.playToServer(EmploymentStateRequestPacket.TYPE, EmploymentStateRequestPacket.STREAM_CODEC, EmploymentStateRequestPacket::handle);
        registrar.playToServer(NpcHireListRequestPacket.TYPE, NpcHireListRequestPacket.STREAM_CODEC, NpcHireListRequestPacket::handle);
        registrar.playToServer(NpcHireAssignPacket.TYPE, NpcHireAssignPacket.STREAM_CODEC, NpcHireAssignPacket::handle);
        registrar.playToServer(NpcHireFirePacket.TYPE, NpcHireFirePacket.STREAM_CODEC, NpcHireFirePacket::handle);
        registrar.playToServer(BuildBoxStartConstructionPacket.TYPE, BuildBoxStartConstructionPacket.STREAM_CODEC, BuildBoxStartConstructionPacket::handle);
        registrar.playToServer(ResidentialControlBoxOpenRequestPacket.TYPE, ResidentialControlBoxOpenRequestPacket.STREAM_CODEC, ResidentialControlBoxOpenRequestPacket::handle);
        registrar.playToServer(ResidentialControlBoxDemolishPacket.TYPE, ResidentialControlBoxDemolishPacket.STREAM_CODEC, ResidentialControlBoxDemolishPacket::handle);
        registrar.playToServer(ResidentialControlBoxOccupancyPacket.TYPE, ResidentialControlBoxOccupancyPacket.STREAM_CODEC, ResidentialControlBoxOccupancyPacket::handle);
        registrar.playToServer(FarmlandBoxOpenRequestPacket.TYPE, FarmlandBoxOpenRequestPacket.STREAM_CODEC, FarmlandBoxOpenRequestPacket::handle);
        registrar.playToServer(FarmlandBoxActionPacket.TYPE, FarmlandBoxActionPacket.STREAM_CODEC, FarmlandBoxActionPacket::handle);
        registrar.playToServer(FarmlandBoxSetCropPacket.TYPE, FarmlandBoxSetCropPacket.STREAM_CODEC, FarmlandBoxSetCropPacket::handle);
        registrar.playToServer(FarmlandBoxSetAreaPacket.TYPE, FarmlandBoxSetAreaPacket.STREAM_CODEC, FarmlandBoxSetAreaPacket::handle);
        registrar.playToServer(FarmlandBoxBoundsRequestPacket.TYPE, FarmlandBoxBoundsRequestPacket.STREAM_CODEC, FarmlandBoxBoundsRequestPacket::handle);
        registrar.playToServer(IndustrialControlBoxOpenRequestPacket.TYPE, IndustrialControlBoxOpenRequestPacket.STREAM_CODEC, IndustrialControlBoxOpenRequestPacket::handle);
        registrar.playToServer(IndustrialControlBoxActionPacket.TYPE, IndustrialControlBoxActionPacket.STREAM_CODEC, IndustrialControlBoxActionPacket::handle);
        registrar.playToServer(IndustrialControlBoxDemolishPacket.TYPE, IndustrialControlBoxDemolishPacket.STREAM_CODEC, IndustrialControlBoxDemolishPacket::handle);
        registrar.playToServer(CommercialControlBoxOpenRequestPacket.TYPE, CommercialControlBoxOpenRequestPacket.STREAM_CODEC, CommercialControlBoxOpenRequestPacket::handle);
        registrar.playToServer(MedicalControlBoxOpenRequestPacket.TYPE, MedicalControlBoxOpenRequestPacket.STREAM_CODEC, MedicalControlBoxOpenRequestPacket::handle);
        registrar.playToServer(CommercialControlBoxActionPacket.TYPE, CommercialControlBoxActionPacket.STREAM_CODEC, CommercialControlBoxActionPacket::handle);
        registrar.playToServer(CommercialControlBoxDemolishPacket.TYPE, CommercialControlBoxDemolishPacket.STREAM_CODEC, CommercialControlBoxDemolishPacket::handle);
        registrar.playToServer(CommercialTradePacket.TYPE, CommercialTradePacket.STREAM_CODEC, CommercialTradePacket::handle);
        registrar.playToServer(LogisticsServerBoxOpenRequestPacket.TYPE, LogisticsServerBoxOpenRequestPacket.STREAM_CODEC, LogisticsServerBoxOpenRequestPacket::handle);
        registrar.playToServer(LogisticsClientBoxOpenRequestPacket.TYPE, LogisticsClientBoxOpenRequestPacket.STREAM_CODEC, LogisticsClientBoxOpenRequestPacket::handle);
        registrar.playToServer(LogisticsBoxActionPacket.TYPE, LogisticsBoxActionPacket.STREAM_CODEC, LogisticsBoxActionPacket::handle);
        registrar.playToServer(LogisticsWarehouseGridOpenRequestPacket.TYPE, LogisticsWarehouseGridOpenRequestPacket.STREAM_CODEC, LogisticsWarehouseGridOpenRequestPacket::handle);
        registrar.playToServer(LogisticsWarehouseGridRequestPacket.TYPE, LogisticsWarehouseGridRequestPacket.STREAM_CODEC, LogisticsWarehouseGridRequestPacket::handle);
        registrar.playToServer(LogisticsWarehouseGridExtractPacket.TYPE, LogisticsWarehouseGridExtractPacket.STREAM_CODEC, LogisticsWarehouseGridExtractPacket::handle);
        registrar.playToServer(LogisticsWarehouseGridInsertPacket.TYPE, LogisticsWarehouseGridInsertPacket.STREAM_CODEC, LogisticsWarehouseGridInsertPacket::handle);
        registrar.playToServer(LogisticsWarehouseGridShiftClickPacket.TYPE, LogisticsWarehouseGridShiftClickPacket.STREAM_CODEC, LogisticsWarehouseGridShiftClickPacket::handle);
        registrar.playToServer(PlannerMaterialScanRequestPacket.TYPE, PlannerMaterialScanRequestPacket.STREAM_CODEC, PlannerMaterialScanRequestPacket::handle);
        registrar.playToServer(CreatePlanningTaskPacket.TYPE, CreatePlanningTaskPacket.STREAM_CODEC, CreatePlanningTaskPacket::handle);
        registrar.playToServer(NpcPathDebugRequestPacket.TYPE, NpcPathDebugRequestPacket.STREAM_CODEC, NpcPathDebugRequestPacket::handle);
        registrar.playToServer(ManifestTogglePacket.TYPE, ManifestTogglePacket.STREAM_CODEC, ManifestTogglePacket::handle);
        registrar.playToServer(ServerConfigSavePacket.TYPE, ServerConfigSavePacket.STREAM_CODEC, ServerConfigSavePacket::handle);
        registrar.playToClient(CityCoreOpenResponsePacket.TYPE, CityCoreOpenResponsePacket.STREAM_CODEC, CityCoreOpenResponsePacket::handle);
        registrar.playToClient(CityCoreMembersResponsePacket.TYPE, CityCoreMembersResponsePacket.STREAM_CODEC, CityCoreMembersResponsePacket::handle);
        registrar.playToClient(CityCitizenManageResponsePacket.TYPE, CityCitizenManageResponsePacket.STREAM_CODEC, CityCitizenManageResponsePacket::handle);
        registrar.playToClient(CityCoreMapResponsePacket.TYPE, CityCoreMapResponsePacket.STREAM_CODEC, CityCoreMapResponsePacket::handle);
        registrar.playToClient(CityChunkSyncPacket.TYPE, CityChunkSyncPacket.STREAM_CODEC, CityChunkSyncPacket::handle);
        registrar.playToClient(NpcHireListResponsePacket.TYPE, NpcHireListResponsePacket.STREAM_CODEC, NpcHireListResponsePacket::handle);
        registrar.playToClient(EmploymentStateResponsePacket.TYPE, EmploymentStateResponsePacket.STREAM_CODEC, EmploymentStateResponsePacket::handle);
        registrar.playToClient(HudSyncPacket.TYPE, HudSyncPacket.STREAM_CODEC, HudSyncPacket::handle);
        registrar.playToClient(BuildingCacheReloadPacket.TYPE, BuildingCacheReloadPacket.STREAM_CODEC, BuildingCacheReloadPacket::handle);
        registrar.playToClient(ResidentialControlBoxBoundsUpdatePacket.TYPE, ResidentialControlBoxBoundsUpdatePacket.STREAM_CODEC, ResidentialControlBoxBoundsUpdatePacket::handle);
        registrar.playToClient(ResidentialControlBoxViewUpdatePacket.TYPE, ResidentialControlBoxViewUpdatePacket.STREAM_CODEC, ResidentialControlBoxViewUpdatePacket::handle);
        registrar.playToClient(ResidentialControlBoxOpenResponsePacket.TYPE, ResidentialControlBoxOpenResponsePacket.STREAM_CODEC, ResidentialControlBoxOpenResponsePacket::handle);
        registrar.playToClient(FarmlandBoxOpenResponsePacket.TYPE, FarmlandBoxOpenResponsePacket.STREAM_CODEC, FarmlandBoxOpenResponsePacket::handle);
        registrar.playToClient(FarmlandBoxBoundsResponsePacket.TYPE, FarmlandBoxBoundsResponsePacket.STREAM_CODEC, FarmlandBoxBoundsResponsePacket::handle);
        registrar.playToClient(IndustrialControlBoxOpenResponsePacket.TYPE, IndustrialControlBoxOpenResponsePacket.STREAM_CODEC, IndustrialControlBoxOpenResponsePacket::handle);
        registrar.playToClient(IndustrialControlBoxViewUpdatePacket.TYPE, IndustrialControlBoxViewUpdatePacket.STREAM_CODEC, IndustrialControlBoxViewUpdatePacket::handle);
        registrar.playToClient(CommercialControlBoxOpenResponsePacket.TYPE, CommercialControlBoxOpenResponsePacket.STREAM_CODEC, CommercialControlBoxOpenResponsePacket::handle);
        registrar.playToClient(MedicalControlBoxOpenResponsePacket.TYPE, MedicalControlBoxOpenResponsePacket.STREAM_CODEC, MedicalControlBoxOpenResponsePacket::handle);
        registrar.playToClient(CommercialTradeOpenResponsePacket.TYPE, CommercialTradeOpenResponsePacket.STREAM_CODEC, CommercialTradeOpenResponsePacket::handle);
        registrar.playToClient(LogisticsServerBoxOpenResponsePacket.TYPE, LogisticsServerBoxOpenResponsePacket.STREAM_CODEC, LogisticsServerBoxOpenResponsePacket::handle);
        registrar.playToClient(LogisticsClientBoxOpenResponsePacket.TYPE, LogisticsClientBoxOpenResponsePacket.STREAM_CODEC, LogisticsClientBoxOpenResponsePacket::handle);
        registrar.playToClient(LogisticsWarehouseGridResponsePacket.TYPE, LogisticsWarehouseGridResponsePacket.STREAM_CODEC, LogisticsWarehouseGridResponsePacket::handle);
        registrar.playToClient(PlannerMaterialScanResponsePacket.TYPE, PlannerMaterialScanResponsePacket.STREAM_CODEC, PlannerMaterialScanResponsePacket::handle);
        registrar.playToClient(NpcPathDebugSyncPacket.TYPE, NpcPathDebugSyncPacket.STREAM_CODEC, NpcPathDebugSyncPacket::handle);
        registrar.playToClient(InfoToastPacket.TYPE, InfoToastPacket.STREAM_CODEC, InfoToastPacket::handle);
    }
}
